Feat/#99 Logbat Java SDK 최소 기능 구현
woowa-techcamp-2024/Team5-Guys pull request #104
Opened 2024-08-21 15:12 UTC by miiiinju1

## 🚀 작업 내용

### AppKey를 application.yml에서 읽어오는 LogbatConfigLoader 구현
- LogbatConfigLoader를 구현하여 application.yml, application.yaml, 또는 application.properties 파일에서 설정 값을 외부 의존성 없이 로드하여 Map<String, String> 형태로 반환하여 사용하도록 구현했습니다. 

### Logback과 Logbat 연동을 위한 LogbatAppender 구현
    - LogbatAppender 클래스를 `UnsynchronizedAppenderBase`를 구현하여 Logback 프레임워크와 Logbat 시스템을 연동했습니다.
    - Logback의 ILoggingEvent를 기반으 로그 메시지, 레벨, 타임스탬프 등을 추출하여 Logbat 시스템에 **비동기적으로 로그를 전송**하도록 설계했습니다.

### LogbatFactory에서 의존성 관리 추가
    - LogbatFactory는 Logbat 인스턴스를 싱글톤으로 관리하며, 이를 위해 LogBuffer, LogSender, AsyncLogWriter의 의존성을 생성하고 주입합니다.
    - LogSender는 HttpClient, ObjectMapper, LogbatOptions와 같은 외부 의존성들을 주입받아 초기화되며, 이들이 모두 LogbatFactory에서 관리됩니다.

###  LogProcessScheduler 클래스에 gracefulShutdown 메서드를 추가하여 JVM 종료 시에도 남아 있는 로그를 안전하게 전송하고 스케줄러를 종료할 수 있도록 구현했습니다.
    - Shutdown Hook을 등록하여 JVM 종료 시 gracefulShutdown 메서드가 자동으로 호출되도록 했습니다.
    - 종료 시 로그 전송 작업을 병렬로 처리하기 위해 추가된 ExecutorService를 사용하여 shutdownExecutor를 생성하고, 모든 작업이 완료될 때까지 대기하는 방식으로 로그 전송의 안정성을 높였습니다.
## 📸 이슈 번호

- close #99 

## 👀 Focus Commits [Optional]

- 커밋해시: 내용

## ✍ 궁금한 점
- 중점적으로 봐줄 내용
- 변수명 괜찮나요
- 로직이 좀 더럽나요
- 가독성이 좀 그런가요?

2024-08-21 16:34 UTC, LuizyHub reviewed
ILoggingEvent 객체를 받아 로그를 전송하는 부분 잘 확인했습니다!

application.properties or yml 에
`logbat.appKey` 값이 필요하겠네요! 리뷰 한번 확인 부탁드리겠습니다

2024-08-21 16:34 UTC, LuizyHub commented on sdk/java/logbat-sdk/src/main/java/info/logbat/LogbatFactory.java
> +public class LogbatFactory {
어차피 생성자가 private라 상속받아도 객체 못만들겠지만, final 키워드도 적용해도 좋을 것 같아요!

2024-08-21 16:34 UTC, LuizyHub commented on sdk/java/logbat-sdk/src/main/java/info/logbat/adapter/logback/LogbatAppender.java
> +        String level = eventObject.getLevel().toString();
OFF, ALL 과 같은 아직 지원하지 않는 로그들이 존재 할 수 있겠군요!

![image](https://github.com/user-attachments/assets/9c1b0983-b8a2-4eba-b8e7-d05477f1cef4)

2024-08-21 16:34 UTC, LuizyHub commented on sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogProcessScheduler.java
> +            logs.addAll(logBuffer.getLogs(DEFAULT_BULK_SIZE));
logBuffer로 부터 받은 로그들을 try 블럭 안에서만 소진하는 생각이 들어서 아래처럼 하지 않으신 이유가 있을까요?
혹시 실패할 경우 `logs` 를 catch 블러 안에서 처리하려고 밖에 빼두신 걸까요?
그렇다면 ` = new ArrayList<>();` 까지는 필요하지 않을 것 같습니다! 
```suggestion
        try {
            List<LogSendRequest> logs = logBuffer.getLogs(DEFAULT_BULK_SIZE);
```

2024-08-21 22:43 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogProcessScheduler.java
> +            logs.addAll(logBuffer.getLogs(DEFAULT_BULK_SIZE));
아! 이 부분을 실패 시 catch 블럭에서 retryQueue까지 넣는 로직으로 구현 계획했으나 이번 PR에서는 제외시킨 부분이라 위와 같이 구현이 되어 있습니다!!

2024-08-21 22:44 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/adapter/logback/LogbatAppender.java
> +        String level = eventObject.getLevel().toString();
맞네요!! 이 부분 필터링 하도록 수정하겠습니다!

2024-08-22 01:32 UTC, LuizyHub approved these changes
추가된 final 키워드와 구체화된 로그 생성문 확인했습니다!
수고하셨습니다~

2024-08-22 02:04 UTC, tidavid1 requested changes
리뷰 봐주시면 감사하겠습니둥

2024-08-22 02:04 UTC, tidavid1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/application/LogSendRequestFactory.java
> +        );
이부분은 메시지를 만들기 위한 부분이라 메서드 분리하는게 좋아 보여요 :D
```java
private String getMessage(ILoggingEvent eventObject, String threadName,
        String formattedLevel) {
        String loggerName = eventObject.getLoggerName();
        Map<String, String> mdcProperties = eventObject.getMDCPropertyMap();
        String mdcString = mdcProperties.isEmpty() ? "" : " MDC: " + mdcProperties;

        String throwableString = "";
        if (eventObject.getThrowableProxy() != null) {
            throwableString = " EXCEPTION: " + eventObject.getThrowableProxy().getMessage();
        }

        String message = String.format(
            "[%s] [%s] %s - %s%s%s",
            threadName, loggerName, formattedLevel, eventObject.getFormattedMessage(),
            mdcString, throwableString
        );
        return message;
    }
```

2024-08-22 02:04 UTC, tidavid1 commented on sdk/java/logbat-sdk/build.gradle
JDK 버전 명시 해주시면 감사하겠습니다.

2024-08-22 02:04 UTC, tidavid1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/AsyncLogWriter.java
> +    private final LogProcessScheduler logProcessScheduler;
이거 대입만 되고 사용은 안하는데 이유가 있을까요?

2024-08-22 02:04 UTC, tidavid1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogProcessScheduler.java
> +    private static final Integer SHUTDOWN_THREAD_POOL_SIZE = 4; // 병렬 처리를 위한 스레드 풀 크기
추후에 이부분도 사용자가 옵티마이징 할 수 있도록 하면 좋을 것 같다는 생각입니다. -> .yml로?

2024-08-22 02:06 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/domain/logbat/AppKey.java
> +        }
좋은 생각인 것 같아요!! AppKey가 유효하지 않으면 어플리케이션을 종료시켜도 좋을 것 같습니다~

2024-08-22 02:06 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/domain/logbat/AppKey.java
> +public class AppKey {
이후 JDK 11로 다운그레이드 계획 있어 다른 record들도 class 불변 객체로 만들어야할 것 같습니다!

2024-08-22 02:08 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/config/LogbatConfig.java
> +}
이 부분은 Sentry SDK에서 착안했는데, 
이후 추가될 수 있는 sampling level이나 전송할 최소 Log Level에 대한 내용을 내부에서 관리하기 위해서 미리 캡슐화 해두었습니다.

2024-08-22 02:11 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogSender.java
> +        this.objectMapper = objectMapper;
LogSender에 대한 테스트를 위해 외부에서 의존성 주입받을 수 있도록 만들었습니다!

2024-08-22 02:12 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/AsyncLogWriter.java
> +    private final LogProcessScheduler logProcessScheduler;
혹시 모를 참조를 위해 남겨두었습니다. 혹시나 new로 생성했을 때 강한 참조가 없어 GC되지 않을까 염려되었습니다.

이 부분에 대해 더 정확하게 찾아봐야할 것 같아요~~

2024-08-22 02:12 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogProcessScheduler.java
> +    private static final Integer SHUTDOWN_THREAD_POOL_SIZE = 4; // 병렬 처리를 위한 스레드 풀 크기
좋습니다~~

2024-08-22 02:15 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/infrastructure/LogSender.java
보통 발생하는 상황이 Bad Request 이외에는 Internal Server Error일 것이라고 생각해서 예외를 던지고, 
외부에서 해당 예외를 잡아서 retryQueue에 넣는 등 추가적인 처리를 하면 좋을 것 같다고 생각했습니다!

이 부분에 관해 어떻게 생각하시나요?

2024-08-22 02:19 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/config/LogbatConfigLoader.java
> +    }
외부 의존성을 최대한 가지지 않으려고 직접 파싱 로직을 추가했습니다!!

application.yml을 파싱하려고 해도 snakeyml이 필요하고, 라이브러리는 최대한 의존성을 안 가지게 가볍게 구현하면 좋을 것 같았습니다.

2024-08-22 02:19 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/application/LogSendRequestFactory.java
> +        );
오 맞네요 이 부분도 클래스 분리하면 좋을 것 같습니다.

2024-08-22 03:26 UTC, miiiinju1 commented on sdk/java/logbat-sdk/src/main/java/info/logbat/domain/logbat/AppKey.java
> +        }
방금 해보려고 했는데, Logback Appender를 초기화할 떄 내부적으로 메인 스레드에서 `start()` 메서드를 호출하기 때문에

Checked Exception으로는 던질 수 없고, Unchecked Exception을 던지면 메인 스레드가 종료되게 유도할 수 있을 것 같습니다!!

2024-08-22 04:24 UTC, tidavid1 approved these changes
스프링에서 테스트 후 반영만 해주세요! 👍🏻

2024-08-22 05:08 UTC, tidavid1 approved these changes

2024-08-22 05:08 UTC, merged